language: java

jdk:
    - oraclejdk8

jobs:
        include:
                - stage: build-with-tests
                  install:
                          mvn --settings .maven.xml install -B 
                - stage: build-with-minimized-libs
                  install:
                          mvn clean deploy --settings .maven.xml -B -PMinimizedDependencies
                - stage: deploy-develop-branch
                  install:
                        mvn clean deploy --settings .maven.xml -B
                  on:
                        branch: develop 
