---
language: java

dist: trusty

jdk:
    - openjdk8

cache:
    directories:
        - $HOME/.m2

jobs:
    include:
        - stage: build-with-tests
          install:
              mvn --settings .maven.xml install -B
        - stage: build-profil-MinimizedDependencies
          install:
              mvn clean install --settings .maven.xml -B -PMinimizedDependencies
        - stage: build-profil-scala_2.11
          install:
              mvn clean install -B -Pscala-2.11
        - stage: deploy-develop-with-profil-MinimizedDependencies
          install:
              mvn clean deploy --settings .maven.xml -B -PMinimizedDependencies
        - stage: deploy-develop
          install:
              mvn clean deploy --settings .maven.xml -B

stages:
    - build-with-tests
    - build-profil-MinimizedDependencies
    - build-profil-scala_2.11
    - name: deploy-develop-with-profil-MinimizedDependencies
      if: branch = develop AND type != pull_request AND sender IN (obermeier)
    - name: deploy-develop
      if: branch = develop AND type != pull_request AND sender IN (obermeier)

deploy:
    provider: script
    script: scray-examples/ingestion/prometheus_crawler/docker_deploy.sh
    skip_cleanup: true
    on:
        all_branches: true
	condition: sender IN (obermeier) OR sender IN (JohannesStrassner) 
