language: java

jdk:
    - oraclejdk8

install:
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V 

script:
    mvn clean deploy --settings .maven.xml -DskipTests=true -B -U
