---
apiVersion: v1
kind: Pod
metadata:
  name: trafficdata-mongodb
  labels:
    app: trafficdata-mongodb
spec:
  containers:
    - name: nrw-traffic-client
      image:  scrayorg/nrw-traffic-client
    - name: mongodb-example-rest
      image: scrayorg/mongodb-example-rest
    - name: mongodb
      image: mongo:4.0
      ports:
       - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: trafficdata-mongodb 
  labels:
    run: trafficdata-mongodb 
spec:
  type: NodePort
  selector:
    app: trafficdata-mongodb
  ports:
  - name: mongodb-rest-writer 
    port: 8080
    nodePort: 30080 
    protocol: TCP
  - name: mongodb 
    port: 27017
    nodePort: 30081
    protocol: TCP
